.class public final Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;
.super Ljava/lang/Object;
.source "AutoGeneratedBindingsForDalvikGcModule.java"

# interfaces
.implements Lcom/facebook/gk/GatekeeperSetProvider;


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 11
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static b()Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;
    .locals 1

    .prologue
    .line 33
    invoke-static {}, Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;->c()Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;

    move-result-object v0

    return-object v0
.end method

.method private static c()Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;
    .locals 1

    .prologue
    .line 25
    new-instance v0, Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;

    invoke-direct {v0}, Lcom/facebook/dalvikgc/AutoGeneratedBindingsForDalvikGcModule$GKProviderForDalvikGcModule;-><init>()V

    return-object v0
.end method


# virtual methods
.method public final a()Lcom/google/common/collect/ImmutableSet;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Lcom/google/common/collect/ImmutableSet",
            "<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .prologue
    .line 16
    const-string v0, "fbandroid_dalvik_gc_instrumentation_enabled"

    invoke-static {v0}, Lcom/google/common/collect/ImmutableSet;->b(Ljava/lang/Object;)Lcom/google/common/collect/ImmutableSet;

    move-result-object v0

    return-object v0
.end method
