.class public final Lcom/facebook/common/gcinitopt/AutoGeneratedBindingsForGcInitOptimizationModule;
.super Ljava/lang/Object;
.source "AutoGeneratedBindingsForGcInitOptimizationModule.java"


# annotations
.annotation runtime Lcom/facebook/inject/AutoGeneratedBinder;
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 9
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 21
    return-void
.end method
